import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from "axios";
import {useState} from "react";

export default function Home({ api }) {
    const [data, setData] = useState({ greeting: '' })

    async function callBackend() {
        const response = await axios.get(`${api}hello`)
        console.log(response.data)
        setData(response.data)
    }

    console.log(process.env.API)

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
            <button onClick={async () => await callBackend()}>fetch data</button>
          Hello from Backend {data.greeting}
        </h1>
      </main>
    </div>
  )
}

export async function getStaticProps() {
    const api = process.env.API
    console.log(api)
    return {
        props: {
            api
        }
    }
}